site_name: База знаний о простой жизни и возвышенном мышлении
docs_dir: src/docs
site_dir: docs
locale: ru
repo_url: https://github.com/ISKCON-developers-community/sattva-life
site_description: База знаний о простой жизни и возвыщенном мышлении
site_author: Atmayoni das
theme:
  name: material
  features:
    - navigation.indexes
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: "#"
nav:
  - Введение: index.md
  - Памятка: help.md
  - Разделы:
    - Сельское хозяйство:
      - agriculture/index.md
      - agriculture/sel-hoz-voen-hoz.md
      - agriculture/vyraschivanie-bobov.md
      - agriculture/vyraschivanie-goroha.md
    - Защита коров:
      - cows/index.md
      - cows/ahimsa-milk-gbc-resolution-2022.md
      - cows/broshura-o-korovah.md
    - Община:
      - community/index.md
      - community/community-64-bsst.md
      - community/community-basic.md
      - community/community-concept.md
      - community/internet-community.md
      - community/rentabelnost.md
      - community/spititual-community.md
    - Здоровье:
      - health/index.md
      - health/milk.md
      - COVID-19:
        - health/COVID-19/index.md
        - health/COVID-19/covid-19.md
        - health/COVID-19/conference.md
        - health/COVID-19/lechenie.md
        - health/COVID-19/podvedenie-itogov-covid.md
        - health/COVID-19/profilaktika.md
        - health/COVID-19/specialists.md
        - health/COVID-19/vitamin.md
        - health/COVID-19/vosstanovlenie.md
    - Гурукула:
      - gurukula/index.md
    - Колледжи варнашрамы:
      - varnasrama-college/index.md
